---
- name: Install wireless and RF analysis tools
  apt:
    name:
      - bluez
      - bluetooth
      - bluez-tools
      - bluez-hcidump
      - aircrack-ng
      - kismet
      - wireshark
      - tshark
      - tcpdump
      - mfoc
      - libnfc-bin
      - libnfc-examples
      - libfreefare-bin
      - libusb-dev
      - pcsc-tools
      - pcscd
      - pcsc-lite-dev
      - libpcsclite1
      - libpcsc-perl
      - python3-pyscard
    state: present

- name: Install Python packages for RF and wireless analysis
  pip:
    name:
      - scapy
      - pybluez
      - pyusb
      - bluepy
    state: present

- name: Create wireless tools directory
  file:
    path: "{{ osint_tools_dir }}/wireless"
    state: directory
    mode: 0755

- name: Download and install Kismet
  git:
    repo: "https://github.com/kismetwireless/kismet.git"
    dest: "{{ osint_tools_dir }}/wireless/kismet"
    update: yes

- name: Configure and build Kismet
  shell: |
    cd {{ osint_tools_dir }}/wireless/kismet
    ./configure
    make -j$(nproc)
    make suidinstall
  args:
    creates: /usr/local/bin/kismet

- name: Create wireless tools control script
  template:
    src: wireless_tools.sh.j2
    dest: "{{ osint_base_dir }}/scripts/wireless_tools.sh"
    mode: 0755