---
- name: Install containerd prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install containerd
  apt:
    name: containerd.io
    state: present

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: 0755

- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Update containerd configuration for cri
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'disabled_plugins = \["cri"\]'
    line: 'disabled_plugins = []'
    state: present

- name: Install CNI plugins
  apt:
    name: containernetworking-plugins
    state: present

- name: Create CNI config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Install nerdctl
  unarchive:
    src: https://github.com/containerd/nerdctl/releases/download/v0.22.2/nerdctl-0.22.2-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    creates: /usr/local/bin/nerdctl

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Create containerd data directory
  file:
    path: /opt/osint/containers
    state: directory
    mode: 0755