---
# Base role tasks
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400  # 24 hours

- name: Install base dependencies
  apt:
    name: "{{ system_packages }}"
    state: present

- name: Configure timezone
  timezone:
    name: "{{ timezone | default('UTC') }}"

- name: Create OSINT directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /opt/osint
    - /opt/osint/tools
    - /opt/osint/data
    - /opt/osint/scripts
    - /opt/osint/logs
    - /opt/osint/containers
    - /opt/osint/secure_creds

# Include security tasks
- import_tasks: security.yml

# Include network tasks
- import_tasks: network.yml

# Include container tasks
- import_tasks: containers.yml
