---
# Specific configuration for an individual OSINT server instance
# This is typically used for unique server-level configurations

# Server identification
server_name: osint-primary
server_role: main_research_instance

# Specific network configuration
network_config:
  primary_interface: eth0
  management_interface: eth1
  vpn_interface: wg0
  
  ip_configuration:
    static_ip: null  # Set to a static IP if needed
    default_gateway: null
    dns_servers:
      - 1.1.1.1
      - 9.9.9.9

# Firewall rules specific to this server
firewall:
  additional_open_ports:
    - 7474/tcp  # Neo4j browser
    - 7687/tcp  # Neo4j bolt
  
  blocked_countries: []  # Optional country-level blocking

# Resource allocation
system_resources:
  cpu_cores_limit: null  # Optional CPU core limit
  memory_limit: null     # Optional memory limit in GB
  swap_limit: null       # Optional swap limit in GB

# Optional monitoring configuration
monitoring:
  enabled: true
  alert_email: null
  slack_webhook: null

# Additional security hardening
security_extras:
  kernel_module_blacklist:
    - bluetooth
    - thunderbolt
  
  disable_ipv6: true
  
  additional_ssh_options:
    - "AllowUsers campo"
    - "DenyUsers root"