---
- name: Install mobile interface requirements
  apt:
    name:
      - ncurses-bin
      - dialog
      - figlet
      - lolcat
    state: present
    
- name: Create mobile interface directory
  file:
    path: "/opt/osint/mobile"
    state: directory
    mode: 0755
    
- name: Copy campo mobile interface script
  template:
    src: campo_menu.sh.j2
    dest: "/usr/local/bin/campo"
    mode: 0755