---
- name: Install dependencies for bbot
  apt:
    name:
      - python3-dev
      - python3-pip
      - git
      - libssl-dev
      - libffi-dev
      - build-essential
    state: present

- name: Clone bbot repository
  git:
    repo: "https://github.com/blacklanternsecurity/bbot.git"
    dest: "{{ osint_tools_dir }}/bbot"
    update: yes

- name: Install bbot requirements
  pip:
    requirements: "{{ osint_tools_dir }}/bbot/requirements.txt"
    state: present

- name: Install bbot in development mode
  command:
    cmd: pip install -e .
    chdir: "{{ osint_tools_dir }}/bbot"
  become: yes

- name: Create bbot config directory
  file:
    path: "{{ osint_base_dir }}/.bbot"
    state: directory
    mode: 0755

- name: Create bbot configuration file
  template:
    src: bbot_config.yml.j2
    dest: "{{ osint_base_dir }}/.bbot/config.yml"
    mode: 0644

- name: Create symbolic link to user's home directory
  file:
    src: "{{ osint_base_dir }}/.bbot"
    dest: "/root/.bbot"
    state: link