---
- name: Install privacy and security tools
  apt:
    name:
      - tor
      - proxychains4
      - privoxy
      - openvpn
      - iptables-persistent
      - bleachbit
      - secure-delete
      - macchanger
      - firejail
      - apparmor
      - apparmor-profiles
      - apparmor-utils
      - lynis
      - rkhunter
      - clamav
      - clamav-daemon
      - chkrootkit
      - auditd
    state: present

- name: Configure Tor as transparent proxy
  template:
    src: torrc.j2
    dest: /etc/tor/torrc
    mode: 0644
  notify: Restart Tor

- name: Configure ProxyChains
  template:
    src: proxychains.conf.j2
    dest: /etc/proxychains4.conf
    mode: 0644

- name: Create Tor switching script
  template:
    src: tor-control.sh.j2
    dest: /usr/local/bin/tor-control
    mode: 0755

- name: Enable AppArmor
  service:
    name: apparmor
    state: started
    enabled: yes

- name: Setup periodic security checks
  cron:
    name: "Daily security scan"
    hour: "3"
    minute: "30"
    job: "/opt/osint/scripts/security_scan.sh > /opt/osint/data/security_reports/$(date +\\%Y-\\%m-\\%d).log 2>&1"

- name: Create security scan script
  template:
    src: security_scan.sh.j2
    dest: "/opt/osint/scripts/security_scan.sh"
    mode: 0755

- name: Create security reports directory
  file:
    path: "/opt/osint/data/security_reports"
    state: directory
    mode: 0755

- name: Configure IP tables for data leak prevention
  template:
    src: iptables-rules.j2
    dest: /etc/iptables/rules.v4
    mode: 0644
  notify: Apply iptables rules

handlers:
  - name: Restart Tor
    service:
      name: tor
      state: restarted

  - name: Apply iptables rules
    shell: iptables-restore < /etc/iptables/rules.v4