---
- name: Install WireGuard
  apt:
    name:
      - wireguard-tools
      - openresolv
      - jq
    state: present

- name: Create WireGuard config directory
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700

- name: Generate WireGuard private key
  shell: |
    wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
    chmod 600 /etc/wireguard/privatekey
  args:
    creates: /etc/wireguard/privatekey

- name: Setup Mullvad configuration
  import_tasks: mullvad.yml

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes