---
- name: Install Neo4j dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - openjdk-11-jre
    state: present
    update_cache: yes

- name: Add Neo4j repository key
  apt_key:
    url: https://debian.neo4j.com/neotechnology.gpg.key
    state: present

- name: Add Neo4j repository
  apt_repository:
    repo: "deb https://debian.neo4j.com stable 4.4"
    state: present
    update_cache: yes

- name: Create Neo4j data directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
  loop:
    - "/opt/osint/data/neo4j/data"
    - "/opt/osint/data/neo4j/logs"
    - "/opt/osint/data/neo4j/import"
    - "/opt/osint/data/neo4j/plugins"

- name: Download Neo4j APOC plugin
  get_url:
    url: "https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.4.0.6/apoc-4.4.0.6-all.jar"
    dest: "/opt/osint/data/neo4j/plugins/apoc-4.4.0.6-all.jar"
    mode: 0644

- name: Create Neo4j container configuration
  template:
    src: neo4j.conf.j2
    dest: /opt/osint/containers/data_storage/config/neo4j.conf
    mode: 0644

- name: Generate Neo4j initial constraints and indexes
  template:
    src: neo4j_init.cypher.j2
    dest: /opt/osint/containers/data_storage/config/neo4j_init.cypher
    mode: 0644

- name: Create Neo4j startup script
  template:
    src: neo4j_startup.sh.j2
    dest: /opt/osint/containers/data_storage/config/neo4j_startup.sh
    mode: 0755