---
- name: Create container volume directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /opt/osint/containers/volumes
    - /opt/osint/containers/volumes/neo4j
    - /opt/osint/containers/volumes/neo4j/data
    - /opt/osint/containers/volumes/neo4j/logs
    - /opt/osint/containers/volumes/neo4j/import

- name: Create container volume README
  copy:
    dest: "/opt/osint/containers/volumes/README.md"
    content: |
      # Container Volumes
      
      This directory contains persistent volumes for containers that need to store data
      outside of the container filesystem.
      
      ## Directory Structure
      
      - `neo4j/`: Neo4j database files
        - `data/`: Database files
        - `logs/`: Log files
        - `import/`: Import directory
      
      ## Notes
      
      Be careful when making changes to these volumes, as they may affect the
      operation of the containers. Always back up important data before making changes.
    mode: 0644

- name: Create container data integration script
  template:
    src: data_integration.sh.j2
    dest: /opt/osint/scripts/data_integration.sh
    mode: 0755

- name: Create Neo4j database initialization script
  template:
    src: neo4j_init.sh.j2
    dest: /opt/osint/scripts/neo4j_init.sh
    mode: 0755

- name: Install Python dependencies for data correlation
  pip:
    name:
      - py2neo
      - pandas
      - networkx
      - matplotlib
      - pyyaml
      - ipaddress
    state: present