---
- name: Moon Security Platform - Base Configuration
  hosts: all
  become: true
  gather_facts: yes
  
  vars_files:
    - ../roles/common/vars/main.yml
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
    
    - name: Install basic packages
      package:
        name: 
          - curl
          - wget
          - git
          - python3-pip
        state: present
      when: ansible_os_family == 'Debian'
  
  roles:
    - role: base
      tags: base
    
    - role: common
      tags: common
    
    - role: network
      tags: network
    
    - role: vpn
      tags: vpn
    
    - role: security
      tags: security
  
  post_tasks:
    - name: Reboot if required
      reboot:
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required | default(false)
