---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400  # 24 hours

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install common packages
  apt:
    name: "{{ system_packages }}"
    state: present

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Create OSINT directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ osint_base_dir }}"
    - "{{ osint_tools_dir }}"
    - "{{ osint_data_dir }}"
    - "{{ osint_scripts_dir }}"
    - "{{ osint_base_dir }}/logs"

- name: Create tools update script
  template:
    src: update-tools.sh.j2
    dest: "{{ osint_base_dir }}/update-tools.sh"
    mode: 0755