---
- name: Create standard data directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "/opt/osint/data"
    - "/opt/osint/data/targets"
    - "/opt/osint/data/exports"
    - "/opt/osint/data/reports"
    - "/opt/osint/data/standardized"
    - "/opt/osint/data/neo4j"
    - "/opt/osint/data/neo4j/data"
    - "/opt/osint/data/neo4j/logs"
    - "/opt/osint/data/neo4j/import"
    - "/opt/osint/data/neo4j/plugins"

- name: Set proper permissions on data directory
  file:
    path: "/opt/osint/data"
    state: directory
    mode: 0755
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    recurse: yes

- name: Create data organizational README
  copy:
    dest: "/opt/osint/data/README.md"
    content: |
      # OSINT Command Center Data Directory
      
      This directory contains all data managed by the OSINT Command Center.
      
      ## Directory Structure
      
      - `targets/`: Target-specific data organized by target name
      - `exports/`: Exported data for sharing or archiving
      - `reports/`: Generated reports and visualizations
      - `standardized/`: Standardized data in a common format
      - `neo4j/`: Neo4j database files for the correlation engine
      
      ## Usage Guidelines
      
      1. Always organize target data under `targets/<target_name>/`
      2. Use the standardized format for data exchange between tools
      3. Keep sensitive data properly secured
      4. Regularly back up important findings
      
      ## Data Retention Policy
      
      For operational security, consider implementing a data retention policy that 
      automatically securely wipes data after a specified time period.
    mode: 0644

- name: Create target directory template
  file:
    path: "/opt/osint/data/targets/template"
    state: directory
    mode: 0755

- name: Create target directory README
  copy:
    dest: "/opt/osint/data/targets/template/README.md"
    content: |
      # Target: [TARGET_NAME]
      
      This directory contains OSINT data for [TARGET_NAME].
      
      ## Collection Summary
      
      - Collection date: [DATE]
      - Scope: [SCOPE]
      - Tools used: [TOOLS]
      
      ## Directory Structure
      
      - `domain/`: Domain and subdomain information
      - `network/`: Network scanning results
      - `identity/`: Identity research findings
      - `web/`: Web analysis results
      
      ## Notes
      
      [Add investigation notes here]
    mode: 0644

- name: Create standardized data schema
  copy:
    dest: "/opt/osint/data/standardized/schema.json"
    content: |
      {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Standardized OSINT Data",
        "description": "Schema for standardized OSINT data across all tools",
        "type": "object",
        "required": ["target", "timestamp", "entities"],
        "properties": {
          "target": {
            "type": "string",
            "description": "Name of the target"
          },
          "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Time when the data was processed"
          },
          "entities": {
            "type": "array",
            "description": "List of entities discovered",
            "items": {
              "$ref": "#/definitions/Entity"
            }
          },
          "relationships": {
            "type": "array",
            "description": "List of relationships between entities",
            "items": {
              "$ref": "#/definitions/Relationship"
            }
          },
          "summary": {
            "type": "object",
            "description": "Summary statistics",
            "properties": {
              "entity_count": {
                "type": "number"
              },
              "relationship_count": {
                "type": "number"
              },
              "tools": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "definitions": {
          "Entity": {
            "type": "object",
            "required": ["id", "type", "value"],
            "properties": {
              "id": {
                "type": "string"
              },
              "type": {
                "type": "string",
                "enum": [
                  "domain", "subdomain", "ip_address", "email", "username", 
                  "person", "organization", "phone", "url", "service",
                  "certificate", "social_media", "file", "hash"
                ]
              },
              "value": {
                "type": "string"
              },
              "source": {
                "type": "string"
              },
              "confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
              },
              "timestamp": {
                "type": "string",
                "format": "date-time"
              },
              "attributes": {
                "type": "object"
              }
            }
          },
          "Relationship": {
            "type": "object",
            "required": ["id", "source_id", "target_id", "type"],
            "properties": {
              "id": {
                "type": "string"
              },
              "source_id": {
                "type": "string"
              },
              "target_id": {
                "type": "string"
              },
              "type": {
                "type": "string",
                "enum": [
                  "contains", "resolves_to", "belongs_to", "communicates_with",
                  "hosts", "redirects_to", "related_to", "same_as", "part_of",
                  "uses", "has_record", "has_vuln", "owns"
                ]
              },
              "source": {
                "type": "string"
              },
              "confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
              },
              "timestamp": {
                "type": "string",
                "format": "date-time"
              },
              "attributes": {
                "type": "object"
              }
            }
          }
        }
      }
    mode: 0644