- name: Install containerd
  apt:
    name:
      - containerd.io
      - nerdctl
    state: present

- name: Configure containerd
  template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
  notify: Restart containerd