# containerd configuration for OSINT Command Center

version = 2

# Root directory for containerd metadata
root = "/var/lib/containerd"
# State directory for containerd state
state = "/run/containerd"
# Path to containerd socket
address = "/run/containerd/containerd.sock"

# grpc configuration
[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

# ttrpc configuration
[ttrpc]
  address = ""
  uid = 0
  gid = 0

# debug configuration
[debug]
  address = ""
  uid = 0
  gid = 0
  level = "info"

# metrics configuration
[metrics]
  address = ""
  grpc_histogram = false

# cgroup configuration
[cgroup]
  path = ""

# disable CRI
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    disable = false

# CNI plugin
  [plugins."io.containerd.grpc.v1.cri".cni]
    bin_dir = "/opt/cni/bin"
    conf_dir = "/etc/cni/net.d"

# registry configuration
  [plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["https://registry-1.docker.io"]

# stream processor
[stream_processors]
  [stream_processors."io.containerd.ocicrypt.decoder.v1.tar"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+encrypted"]
    returns = ["application/vnd.oci.image.layer.v1.tar"]
  [stream_processors."io.containerd.ocicrypt.decoder.v1.tar.gzip"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+gzip+encrypted"]
    returns = ["application/vnd.oci.image.layer.v1.tar+gzip"]

# timeout settings
[timeouts]
  "io.containerd.timeout.shim.cleanup" = "5s"
  "io.containerd.timeout.shim.load" = "5s"
  "io.containerd.timeout.shim.shutdown" = "3s"
  "io.containerd.timeout.task.state" = "2s"

# stream processor settings
[stream_processors]
  [stream_processors."io.containerd.ocicrypt.decoder.v1.tar"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+encrypted"]
    returns = ["application/vnd.oci.image.layer.v1.tar"]
  [stream_processors."io.containerd.ocicrypt.decoder.v1.tar.gzip"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+gzip+encrypted"]
    returns = ["application/vnd.oci.image.layer.v1.tar+gzip"]

# runtime handler
[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"
  default_runtime_name = "runc"
  
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
      runtime_type = "io.containerd.runc.v2"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
        SystemdCgroup = true