---
- name: Initialize OSINT Command Center system
  hosts: osint_servers
  become: yes
  
  tasks:
    - name: Include base setup
      import_playbook: server_setup.yml
    
    - name: Include containerd setup
      import_playbook: containerd_setup.yml
    
    - name: Include security enhancements
      import_playbook: security_enhancements.yml
    
    - name: Include data correlation setup
      import_playbook: data_correlation.yml
    
    - name: Copy system scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0755
      loop:
        - { src: "../scripts/container_orchestration.sh", dest: "/opt/osint/scripts/container_orchestration.sh" }
        - { src: "../scripts/system_integration.sh", dest: "/opt/osint/scripts/system_integration.sh" }
    
    - name: Install Python requirements for terminal interface
      pip:
        name:
          - py2neo
          - pandas
          - networkx
          - matplotlib
          - requests
          - ipaddress
        state: present
    
    - name: Create system services for container management
      copy:
        dest: "/etc/systemd/system/osint-containers.service"
        content: |
          [Unit]
          Description=OSINT Command Center Containers
          After=network.target containerd.service
          
          [Service]
          Type=oneshot
          ExecStart=/opt/osint/scripts/container_orchestration.sh start
          ExecStop=/opt/osint/scripts/container_orchestration.sh stop
          RemainAfterExit=yes
          
          [Install]
          WantedBy=multi-user.target
        mode: 0644
      notify: Enable container service
    
    - name: Initialize system after setup
      shell: /opt/osint/scripts/system_integration.sh init
      args:
        creates: /opt/osint/data/.initialized
    
    - name: Create initialization flag
      file:
        path: /opt/osint/data/.initialized
        state: touch
        mode: 0644
  
  handlers:
    - name: Enable container service
      systemd:
        name: osint-containers
        enabled: yes
        daemon_reload: yes